name: ghost-dl
on:
  push:
    tags:
      - '*'
jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Build Executable
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: ghost_dl.py
          mode: onefile

        # Both `${{ !contains('windows',matrix.os) }}` and `contains('windows',matrix.os) == false` didn't work, so just working around it
      - if: matrix.os == 'macos-latest'
        name: Rename Binary & Delete Build Directories (MacOS)
        run: mv build/ghost_dl.bin build/ghost-dl && ls build/ && rm -r build/*.build build/*.dist build/*.onefile-build
      - if: matrix.os == 'ubuntu-latest'
        name: Rename Binary & Delete Build Directories (Linux)
        run: mv build/ghost_dl.bin build/ghost-dl && ls build/ && rm -r build/*.build build/*.dist build/*.onefile-build
      - if: matrix.os == 'windows-latest'
        name: Rename Binary (Windows)
        run: mv build/ghost_dl.exe build/ghost-dl.exe     

      - if: matrix.os == 'macos-latest'
        name: Upload Artifacts (MacOS)
        uses: actions/upload-artifact@v4
        with:
          name: ghost-dl_${{ matrix.os }}_${{ github.ref_name }}
          path: build/ghost-dl
          include-hidden-files: true
      - if: matrix.os == 'ubuntu-latest'
        name: Upload Artifacts (Linux)
        uses: actions/upload-artifact@v4
        with:
          name: ghost-dl_${{ matrix.os }}_${{ github.ref_name }}
          path: build/ghost-dl
          include-hidden-files: true
      - if: matrix.os == 'windows-latest'
        name: Upload Artifacts (Windows)
        uses: actions/upload-artifact@v4
        with:
          name: ghost-dl_${{ matrix.os }}_${{ github.ref_name }}
          path: build/ghost-dl.exe
          include-hidden-files: true

      - name: Download LICENSE from Repo
        run: curl https://raw.githubusercontent.com/TheElevatedOne/ghost-dl/refs/heads/main/LICENSE -o build/LICENSE

      - if: matrix.os == 'macos-latest'
        name: Create Tar Archives (MacOS)
        run: tar -czvf ghost-dl_${{ matrix.os }}.tar.gz -C build .
      - if: matrix.os == 'ubuntu-latest'
        name: Create Tar Archives (Linux)
        run: tar -czvf ghost-dl_${{ matrix.os }}.tar.gz -C build .
      - if: matrix.os == 'windows-latest'
        name: Create Tar Archives (Windows)
        run: tar -czvf ghost-dl_${{ matrix.os }}.tar.gz -C build .

      - name: Create Github Release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          artifacts: ghost-dl_${{ matrix.os }}.tar.gz
          replacesArtifacts: false
          name: ${{ github.ref_name }} - ghost_dl
          bodyFile: "RELEASE_BODY.md"
          allowUpdates: true
